---
version: '2'
services:
  firefox:
    image: selenium/node-firefox
    depends_on:
      - automation_hub
    environment:
      HUB_HOST: automation_hub
    networks:
      - hub_network
  chrome:
    image: selenium/node-chrome
    depends_on:
      - automation_hub
    environment:
      HUB_HOST: automation_hub
    networks:
      - hub_network
  automation_hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - hub_network
  automation_build:
    image: maven:3.3-jdk-8
    volumes:
      - ./selenium-grid:/usr/src/mymaven
      - $HOME/.m2:/root/.m2
    working_dir: /usr/src/mymaven
    command: mvn test
    networks:
      - hub_network

networks:
  hub_network: